services:
  vaultwarden:
    image: vaultwarden/server:latest
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - ${PORT}:3012
      - ${HTTP_PORT}:80
    volumes:
      - ${DATA_DIR}/data/:/data/
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DOMAIN=${DOMAIN}
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
networks: {}
