services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_DIR}/db_data:/var/lib/postgresql/data
  nextcloud:
    build: ../dockerfiles/nextcloud/ # same as nextcloud:latest + latest ffmpeg
    # image: nextcloud:latest
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    links:
      - db
    volumes:
      - ${DATA_DIR}/user_data:/var/www/html
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
  go-vod:
    image: radialapps/go-vod
    pull_policy: always
    restart: always
    init: true
    ports:
      - 47788:47788
    depends_on:
      - nextcloud
    environment:
      - NEXTCLOUD_HOST=${NEXTCLOUD_HOST}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${DATA_DIR}/user_data:/var/www/html:ro
    # Uncomment the following lines for QSV / VA-API:
    # devices:
    #  - /dev/dri:/dev/dri

    # Uncomment the following lines for NVENC
    runtime: nvidia
networks: {}
